/* Rahat OS service worker — generated by vite.config.js from scripts/sw.template.js.
 *
 *   navigations         network first, cached app shell when offline
 *   /portfolio/build/*  cache first (file names are content-hashed)
 *   same-origin static  stale-while-revalidate (tools.json, images, icons)
 *   Google Fonts        stale-while-revalidate
 *   everything else     straight to the network, never cached — live APIs
 *                       (weather, prices, the Apps Script index, AI) must not
 *                       answer from a stale copy.
 */
const VERSION = 'ac10ac2c0c';
const BASE = '/portfolio/';
const PRECACHE = ["/portfolio/","/portfolio/index.html","/portfolio/manifest.webmanifest","/portfolio/tools.json","/portfolio/bookmarks.json","/portfolio/assets/favicon.svg","/portfolio/assets/img/profile.jpg","/portfolio/assets/icons/icon-192.png","/portfolio/assets/icons/icon-512.png","/portfolio/build/Atmosphere-KlOelB6R.js","/portfolio/build/AutoLab-B6BpPmXU.js","/portfolio/build/BeamLab-DgTnPgmB.js","/portfolio/build/ControlPanel-DYHtfvGi.js","/portfolio/build/Core3D-Cdh7yO0u.js","/portfolio/build/EngineLab-CgylN-jR.js","/portfolio/build/HeroCanvas-C5JE3GN2.js","/portfolio/build/PipeLab-BgKOpQSy.js","/portfolio/build/Rocket-BpUM-LiO.js","/portfolio/build/RocketLab-D7ICEPWO.js","/portfolio/build/Stage-BLz2IAvV.js","/portfolio/build/SystemsSection-D_37_CnX.js","/portfolio/build/__vite-browser-external-BIHI7g3E.js","/portfolio/build/assemblies-s9H5e709.js","/portfolio/build/index-DE0_vQOk.css","/portfolio/build/index-DLDzBzXf.js","/portfolio/build/r3f-n0XBDWvF.js","/portfolio/build/react-Ek6MvlVl.js","/portfolio/build/three-Cl9kVRY8.js","/portfolio/build/useDragGuard-CIXLhScG.js"];
const SHELL = `rahat-os-shell-${VERSION}`;
const RUNTIME = 'rahat-os-runtime';

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches
      .open(SHELL)
      // One failed optional file must not block installation.
      .then((c) => Promise.all(PRECACHE.map((u) => c.add(new Request(u, { cache: 'reload' })).catch(() => null))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('rahat-os-shell-') && k !== SHELL).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

async function networkFirst(req) {
  try {
    // no-cache: always revalidate the page with the server, so a fresh deploy
    // is picked up on the next refresh instead of a 10-minute-old HTTP copy.
    const res = await fetch(req.url, { cache: 'no-cache', credentials: 'same-origin' });
    if (res.ok) (await caches.open(SHELL)).put(BASE + 'index.html', res.clone());
    return res;
  } catch {
    return (await caches.match(BASE + 'index.html')) || (await caches.match(BASE)) || Response.error();
  }
}

async function cacheFirst(req) {
  const hit = await caches.match(req);
  if (hit) return hit;
  const res = await fetch(req);
  if (res.ok) (await caches.open(RUNTIME)).put(req, res.clone());
  return res;
}

async function staleWhileRevalidate(req) {
  const hit = await caches.match(req);
  const net = fetch(req)
    .then(async (res) => {
      if (res.ok || res.type === 'opaque') (await caches.open(RUNTIME)).put(req, res.clone());
      return res;
    })
    .catch(() => hit || Response.error());
  return hit || net;
}

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  if (url.origin === location.origin && url.pathname.startsWith(BASE)) {
    if (req.mode === 'navigate') return e.respondWith(networkFirst(req));
    if (url.pathname.startsWith(BASE + 'build/')) return e.respondWith(cacheFirst(req));
    if (url.pathname === BASE + 'sw.js') return;
    return e.respondWith(staleWhileRevalidate(req));
  }
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') return e.respondWith(staleWhileRevalidate(req));
  // Anything else (live data, AI, Apps Script) is left to the network.
});
