/* Rahat OS service worker — generated by vite.config.js from scripts/sw.template.js.
 *
 *   navigations         network first, cached app shell when offline
 *   /portfolio/build/*  cache first (file names are content-hashed)
 *   same-origin static  stale-while-revalidate (tools.json, images, icons)
 *   Google Fonts        stale-while-revalidate
 *   everything else     straight to the network, never cached — live APIs
 *                       (weather, prices, the Apps Script index, AI) must not
 *                       answer from a stale copy.
 */
const VERSION = '250e26a628';
const BASE = '/portfolio/';
const PRECACHE = ["/portfolio/","/portfolio/index.html","/portfolio/manifest.webmanifest","/portfolio/tools.json","/portfolio/bookmarks.json","/portfolio/assets/favicon.svg","/portfolio/assets/img/profile.jpg","/portfolio/assets/icons/icon-192.png","/portfolio/assets/icons/icon-512.png","/portfolio/build/Atmosphere-CBYHEa0C.js","/portfolio/build/AutoLab-Df9jxO7G.js","/portfolio/build/BeamLab-qskivzlg.js","/portfolio/build/ControlPanel-xNCRmChX.js","/portfolio/build/EngineLab-BVvzYBB-.js","/portfolio/build/HeroCanvas-DxGDo2kz.js","/portfolio/build/PipeLab-BF3JTLxi.js","/portfolio/build/Rocket-WGRKo6Ev.js","/portfolio/build/RocketLab-BQ6Zp3F-.js","/portfolio/build/Stage-Hgc6uqbZ.js","/portfolio/build/SystemsSection-BmW0l3n8.js","/portfolio/build/__vite-browser-external-BIHI7g3E.js","/portfolio/build/assemblies-BgGuuyCq.js","/portfolio/build/index--WZf0S3I.css","/portfolio/build/index-DVSqg4HP.js","/portfolio/build/r3f-BeTq0b4z.js","/portfolio/build/react-2aQwQ186.js","/portfolio/build/three-Bj-NaVDc.js","/portfolio/build/useDragGuard-DzpeCwAi.js"];
const SHELL = `rahat-os-shell-${VERSION}`;
const RUNTIME = 'rahat-os-runtime';

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches
      .open(SHELL)
      // One failed optional file must not block installation.
      .then((c) => Promise.all(PRECACHE.map((u) => c.add(new Request(u, { cache: 'reload' })).catch(() => null))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('rahat-os-shell-') && k !== SHELL).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

async function networkFirst(req) {
  try {
    const res = await fetch(req);
    if (res.ok) (await caches.open(SHELL)).put(BASE + 'index.html', res.clone());
    return res;
  } catch {
    return (await caches.match(BASE + 'index.html')) || (await caches.match(BASE)) || Response.error();
  }
}

async function cacheFirst(req) {
  const hit = await caches.match(req);
  if (hit) return hit;
  const res = await fetch(req);
  if (res.ok) (await caches.open(RUNTIME)).put(req, res.clone());
  return res;
}

async function staleWhileRevalidate(req) {
  const hit = await caches.match(req);
  const net = fetch(req)
    .then(async (res) => {
      if (res.ok || res.type === 'opaque') (await caches.open(RUNTIME)).put(req, res.clone());
      return res;
    })
    .catch(() => hit || Response.error());
  return hit || net;
}

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  if (url.origin === location.origin && url.pathname.startsWith(BASE)) {
    if (req.mode === 'navigate') return e.respondWith(networkFirst(req));
    if (url.pathname.startsWith(BASE + 'build/')) return e.respondWith(cacheFirst(req));
    if (url.pathname === BASE + 'sw.js') return;
    return e.respondWith(staleWhileRevalidate(req));
  }
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') return e.respondWith(staleWhileRevalidate(req));
  // Anything else (live data, AI, Apps Script) is left to the network.
});
